// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC32TrTqhkGTBmpqgl9SfUmgOdDrrOcUpw',
    appId: '1:965611862391:android:103b0380a90972ca988972',
    messagingSenderId: '965611862391',
    projectId: 'onedir-42e14',
    databaseURL: 'https://onedir-42e14-default-rtdb.firebaseio.com',
    storageBucket: 'onedir-42e14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvChif2TmxjYAJmamLc0bEpkR5lttdQOs',
    appId: '1:965611862391:ios:6bd6f81a258e0b04988972',
    messagingSenderId: '965611862391',
    projectId: 'onedir-42e14',
    databaseURL: 'https://onedir-42e14-default-rtdb.firebaseio.com',
    storageBucket: 'onedir-42e14.appspot.com',
    iosClientId: '965611862391-rnndb7atpptfe9tr7hcuv03lln1p4bug.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineEdir',
  );
}
